notes/models.py
import datetime as dt

from .db import db


class Category(db.Model):
    __tablename__ = "categories"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String, nullable=True, unique=True)
    created_at = db.Column(db.DateTime, default=dt.datetime.utcnow)

    def __str__(self):
        return self.name

    def __repr__(self):
        return f"<Category id={self.id} name={self.name}>"


class Note(db.Model):
    __tablename__ = "notes"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    title = db.Column(db.String, nullable=False)
    content = db.Column(db.Text, nullable=False)
    category_id = db.Column(
        db.Integer, db.ForeignKey("categories.id", ondelete="CASCADE"), nullable=True
    )
    created_at = db.Column(db.DateTime, default=dt.datetime.utcnow)

    category = db.relationship("Category", backref=db.backref("notes", lazy=True), lazy=False)

    def __str__(self):
        return self.title

    def __repr__(self):
        return f"<Note id={self.id} title={self.title}>"

notes/__init__.py
from flask import Flask

from .db import db, migrate
from .controllers import register_blueprints

# init app and configuration
app = Flask(__name__)
app.config['SQLALCHEMY_ECHO'] = True
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///app.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

# init services
db.init_app(app)
migrate.init_app(app, db)

# register controllers/blueprints
register_blueprints(app)

notes/controllers/__init__.py
from flask import Flask

from .categories import categories_blueprint
from .home import home_blueprint
from .notes import notes_blueprint


def register_blueprints(app: Flask):
    app.register_blueprint(home_blueprint)
    app.register_blueprint(notes_blueprint, url_prefix="/notes")
    app.register_blueprint(categories_blueprint, url_prefix="/categories")

notes/controllers/categories.py
from flask import Blueprint, render_template, request, redirect, url_for

from ..db import db
from ..models import Category

categories_blueprint = Blueprint("categories", __name__)


@categories_blueprint.route("", endpoint="index")
def get_list():
    categories = Category.query.all()

    return render_template("categories/index.html", categories=categories)


@categories_blueprint.route("/create", methods=["GET", "POST"])
def create():
    category = Category()

    context = {"category": category}

    if request.method == "POST":
        category.name = request.form["name"]

        if len(category.name) < 3:
            error = "Please check your form. All fields are required."
            context["error"] = error
            return render_template("categories/create.html", **context)

        try:
            db.session.add(category)
            db.session.commit()
        except Exception as err:
            context["error"] = str(err)
            return render_template("categories/create.html", **context)

        return redirect(url_for("categories.index"))

    return render_template("categories/create.html", **context)


@categories_blueprint.route("/<int:category_id>/edit", methods=["GET", "POST"])
def edit(category_id):
    category = Category.query.get_or_404(category_id)

    context = {"category": category}

    if request.method == "POST":
        category.name = request.form["name"]

        if len(category.name) < 3:
            error = "Please check your form. All fields are required."
            context["error"] = error
            return render_template("categories/edit.html", **context)

        try:
            # db.session.add(category)
            db.session.commit()
        except Exception as err:
            context["error"] = str(err)
            return render_template("categories/edit.html", **context)

        return redirect(url_for("categories.index"))

    return render_template("categories/edit.html", **context)

notes/controllers/home.py
from flask import Blueprint, render_template

home_blueprint = Blueprint("home", __name__)


@home_blueprint.route("/")
def index():
    app_name = "Notes App"
    app_description = "Notes management application"

    return render_template("index.html", name=app_name, description=app_description)

notes/controllers/notes.py
import typing

from flask import Blueprint, render_template, request, redirect, url_for

from ..db import db
from ..models import Note, Category


notes_blueprint = Blueprint("notes", __name__)


def format_notes(notes: typing.List[Note]):
    return [dict(id=note.id, title=note.title, content=note.content) for note in notes]


@notes_blueprint.route("/", endpoint="index")
def get_list():
    notes = Note.query.all()

    return render_template("notes/index.html", notes=notes)


@notes_blueprint.route("/create", methods=["GET", "POST"])
def create():
    if request.method == "POST":
        title = request.form["title"]
        content = request.form["content"]

        if len(title) < 3 or len(content) < 3:
            error = "Please check your form. All fields are required."
            return render_template("notes/create.html", error=error, title=title, content=content)

        note = Note(
            title=title,
            content=content,
            category_id=request.form.get("category_id", None)
        )

        db.session.add(note)
        db.session.commit()

        return redirect(url_for("notes.show", note_id=note.id))

    categories = Category.query.all()
    return render_template("notes/create.html", categories=categories, title="", content="")


@notes_blueprint.route("/<int:note_id>", endpoint="show")
def get_one(note_id):
    note = Note.query.get_or_404(note_id)

    return render_template("notes/show.html", note=note)


@notes_blueprint.route("/<int:note_id>/edit", methods=["GET", "POST"])
def edit(note_id):
    note = Note.query.get_or_404(note_id)
    categories = Category.query.all()

    if request.method == "POST":
        title = request.form["title"]
        content = request.form["content"]

        note.category_id = request.form.get("category_id")

        if len(title) < 3 or len(content) < 3:
            error = "Please check your form. All fields are required."

            note.title = title
            note.content = content

            return render_template("notes/edit.html", categories=categories, error=error, note=note)

        note.title = title
        note.content = content

        db.session.add(note)
        db.session.commit()

        return redirect(url_for("notes.show", note_id=note.id))

    return render_template("notes/edit.html", categories=categories, note=note)


@notes_blueprint.route("/<int:note_id>/remove")
def remove(note_id):
    note = Note.query.get_or_404(note_id)

    db.session.delete(note)
    db.session.commit()

    return redirect(url_for("notes.index"))

notes/routes.py
from . import app, controllers

app.add_url_rule("/", "index", controllers.index)
app.add_url_rule("/notes", "notes", controllers.notes)

notes/templates/_partials/footer.html
<footer class="bg-light">
    <div class="container py-3">
        <p class="text-muted m-0">&copy; 2020 Beetroot Academy</p>
    </div>
</footer>

notes/templates/_partials/header.html
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-info">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('home.index') }}">Notes App</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('home.index') }}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link"
                           href="{{ url_for('notes.index') }}">Notes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('categories.index') }}">Categories</a>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search"
                           placeholder="Search" aria-label="Search">
                    <button class="btn btn-light my-2 my-sm-0" type="submit">Search
                    </button>
                </form>
            </div>
        </div>
    </nav>
</header>

notes/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>{% block title %}Notes App{% endblock %}</title>
  </head>
  <body>
    {% include "_partials/header.html" %}

    <div class="container my-5">
      {% block content %}{% endblock %}
    </div>

    {% include "_partials/footer.html" %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

notes/templates/categories/_form.html
<div class="form-group">
    <label for="name">Category name</label>
    <input
        type="text"
        class="form-control"
        id="name"
        name="name"
        placeholder="My note category"
        value="{{ category.name | default("", true) }}"
    />
</div>

<button type="submit" class="btn btn-primary">Save</button>

notes/templates/categories/create.html
{% extends "base.html" %}

{% block title %}Create note category{% endblock %}

{% block content %}
    <div class="d-flex flex-row justify-content-between align-items-center">
        <h1>Create a new note category</h1>
        <a href="{{ url_for('categories.index') }}" class="btn btn-secondary">Back</a>
    </div>

    {% if error %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{ error }}

            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}

    <form action="{{ url_for("categories.create") }}" method="post">
        {% include "categories/_form.html" with context %}
    </form>
{% endblock %}

notes/templates/categories/edit.html
{% extends "base.html" %}

{% block title %}Edit {{ category.name }} category{% endblock %}

{% block content %}
    <div class="d-flex flex-row justify-content-between align-items-center">
        <h1>Edit the <em>{{ category.name }}</em> category</h1>
        <a href="{{ url_for('categories.index') }}" class="btn btn-secondary">Back</a>
    </div>

    {% if error %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{ error }}

            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}

    <form action="{{ url_for("categories.edit", category_id=category.id) }}" method="post">
        {% include "categories/_form.html" with context %}
    </form>
{% endblock %}

notes/templates/categories/index.html
{% extends "base.html" %}

{% block content %}
    <div class="d-flex flex-row justify-content-between align-items-center">
        <h1>My note categories</h1>
        <a href="{{ url_for('categories.create') }}" class="btn btn-info">Create</a>
    </div>

    <ul class="mt-4 list-group">
        {% for category in categories %}
            <li class="list-group-item list-group-item-action">
                {{ category.name }}
                <a href="{{ url_for(".edit", category_id=category.id) }}" class="btn btn-link btn-sm">Edit</a>
            </li>
        {% else %}
            <li class="list-group-item list-group-item-action disabled" aria-disabled="true">
                No note categories.
            </li>
        {% endfor %}
    </ul>
{% endblock %}

notes/templates/index.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ name }}</h1>
    <p>{{ description }}</p>
{% endblock %}

notes/templates/notes/create.html
{% extends "base.html" %}

{% block title %}Create note{% endblock %}

{% block content %}
    <div class="d-flex flex-row justify-content-between align-items-center">
        <h1>Create a new note</h1>
        <a href="{{ url_for('notes.index') }}" class="btn btn-secondary">Back</a>
    </div>

    {% if error %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{ error }}

            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}

    <form action="{{ url_for("notes.create") }}" method="post">
        <div class="form-group">
            <label for="title">Note title</label>
            <input
                type="text"
                class="form-control"
                id="title"
                name="title"
                placeholder="My note"
                value="{{ title }}"
            />
        </div>

        <div class="form-group">
            <label for="category">Category</label>
            <select name="category_id" id="category" class="form-control">
                <option>---</option>
                {% for category in categories %}
                    <option value="{{ category.id }}">{{ category.name }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="form-group">
            <label for="content">Note content</label>
            <textarea class="form-control" name="content" id="content" rows="6">{{ content }}</textarea>
        </div>

        <button type="submit" class="btn btn-primary">Create</button>
    </form>
{% endblock %}

notes/templates/notes/edit.html
{% extends "base.html" %}

{% block title %}Edit {{ note.id }}{% endblock %}

{% block content %}
    <div class="d-flex flex-row justify-content-between align-items-center">
        <h1>Edit {{ note.title }}</h1>
        <a href="{{ url_for('notes.index') }}" class="btn btn-secondary">Back</a>
    </div>

    {% if error %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{ error }}

            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}

    <form action="{{ url_for("notes.edit", note_id=note.id) }}" method="post">
        <div class="form-group">
            <label for="title">Note title</label>
            <input
                type="text"
                class="form-control"
                id="title"
                name="title"
                placeholder="My note"
                value="{{ note.title }}"
            />
        </div>

        <div class="form-group">
            <label for="category">Category</label>
            <select name="category_id" id="category" class="form-control">
                <option>---</option>
                {% for category in categories %}
                    <option
                            value="{{ category.id }}"
                            {% if category.id == note.category_id %} selected {% endif %}
                    >
                        {{ category.name }}
                    </option>
                {% endfor %}
            </select>
        </div>

        <div class="form-group">
            <label for="content">Note content</label>
            <textarea class="form-control" name="content" id="content" rows="6">{{ note.content }}</textarea>
        </div>

        <button type="submit" class="btn btn-primary">Save</button>
    </form>
{% endblock %}

notes/templates/notes/index.html
{% extends "base.html" %}

{% block content %}
    <div class="d-flex flex-row justify-content-between align-items-center">
        <h1>My notes</h1>
        <a href="{{ url_for('notes.create') }}" class="btn btn-info">Create</a>
    </div>

    <div class="mt-4 list-group">
        {% for note in notes %}
            <a href="{{ url_for('notes.show', note_id=note.id) }}" class="list-group-item list-group-item-action">
                {{ note.title }} {% if note.category_id %} - {{ note.category.name }}{% endif %}
            </a>
        {% else %}
            <a class="list-group-item list-group-item-action disabled" aria-disabled="true">
                No notes.
            </a>
        {% endfor %}
    </div>
{% endblock %}

notes/templates/notes/show.html
{% extends "base.html" %}

{% block title %}{{ note.title }}{% endblock %}

{% block content %}
    <div class="d-flex flex-row justify-content-between align-items-center">
        <h1>{{ note.title }}</h1>

        <div class="btn-group" role="group" aria-label="Basic example">
            <a href="{{ url_for('notes.index') }}" class="btn btn-secondary">Back</a>
            <a href="{{ url_for('notes.edit', note_id=note.id) }}" class="btn btn-info">Edit</a>
            <a
                href="{{ url_for('notes.remove', note_id=note.id) }}"
                class="btn btn-danger"
                onclick="return confirm('Do you really want to delete this note?');"
            >Delete</a>
        </div>
    </div>

    <div class="mt-4">
        <p>{{ note.content | safe }}</p>
    </div>
{% endblock %}